version: '3.8'
services: 
    web:
        image: ssspro/iss_tracker:midproj
        build:
            context: .
            dockerfile: ./Dockerfile
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1